// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using PAS.MarketData.Client.Currencies.Rates;
using PAS.MarketData.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace PAS.MarketData.Client.Currencies
{
    /// <summary>
    /// Builds and executes requests for operations under \currencies
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CurrenciesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The rates property</summary>
        public global::PAS.MarketData.Client.Currencies.Rates.RatesRequestBuilder Rates
        {
            get => new global::PAS.MarketData.Client.Currencies.Rates.RatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PAS.MarketData.Client.Currencies.CurrenciesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CurrenciesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/currencies{?pageNumber*,pageSize*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PAS.MarketData.Client.Currencies.CurrenciesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CurrenciesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/currencies{?pageNumber*,pageSize*}", rawUrl)
        {
        }
        /// <summary>
        /// Get a paginated list of currencies.
        /// </summary>
        /// <returns>A <see cref="global::PAS.MarketData.Client.Models.GetCurrencyListResult"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::PAS.MarketData.Client.Models.ValidationProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::PAS.MarketData.Client.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::PAS.MarketData.Client.Models.GetCurrencyListResult?> GetAsync(Action<RequestConfiguration<global::PAS.MarketData.Client.Currencies.CurrenciesRequestBuilder.CurrenciesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::PAS.MarketData.Client.Models.GetCurrencyListResult> GetAsync(Action<RequestConfiguration<global::PAS.MarketData.Client.Currencies.CurrenciesRequestBuilder.CurrenciesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::PAS.MarketData.Client.Models.ValidationProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::PAS.MarketData.Client.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::PAS.MarketData.Client.Models.GetCurrencyListResult>(requestInfo, global::PAS.MarketData.Client.Models.GetCurrencyListResult.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a new currency.
        /// </summary>
        /// <returns>A <see cref="global::PAS.MarketData.Client.Models.CreateCurrencyResult"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::PAS.MarketData.Client.Models.ValidationProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::PAS.MarketData.Client.Models.ProblemDetails">When receiving a 409 status code</exception>
        /// <exception cref="global::PAS.MarketData.Client.Models.ProblemDetails">When receiving a 422 status code</exception>
        /// <exception cref="global::PAS.MarketData.Client.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::PAS.MarketData.Client.Models.CreateCurrencyResult?> PostAsync(global::PAS.MarketData.Client.Models.CreateCurrencyCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::PAS.MarketData.Client.Models.CreateCurrencyResult> PostAsync(global::PAS.MarketData.Client.Models.CreateCurrencyCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::PAS.MarketData.Client.Models.ValidationProblemDetails.CreateFromDiscriminatorValue },
                { "409", global::PAS.MarketData.Client.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "422", global::PAS.MarketData.Client.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::PAS.MarketData.Client.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::PAS.MarketData.Client.Models.CreateCurrencyResult>(requestInfo, global::PAS.MarketData.Client.Models.CreateCurrencyResult.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a paginated list of currencies.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::PAS.MarketData.Client.Currencies.CurrenciesRequestBuilder.CurrenciesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::PAS.MarketData.Client.Currencies.CurrenciesRequestBuilder.CurrenciesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create a new currency.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::PAS.MarketData.Client.Models.CreateCurrencyCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::PAS.MarketData.Client.Models.CreateCurrencyCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::PAS.MarketData.Client.Currencies.CurrenciesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::PAS.MarketData.Client.Currencies.CurrenciesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::PAS.MarketData.Client.Currencies.CurrenciesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get a paginated list of currencies.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CurrenciesRequestBuilderGetQueryParameters 
        {
            [QueryParameter("pageNumber")]
            public int? PageNumber { get; set; }
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CurrenciesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::PAS.MarketData.Client.Currencies.CurrenciesRequestBuilder.CurrenciesRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CurrenciesRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
