// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace PAS.MarketData.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpsertCurrencyRateCommand : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The baseCurrencyId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BaseCurrencyId { get; set; }
#nullable restore
#else
        public string BaseCurrencyId { get; set; }
#endif
        /// <summary>The date property</summary>
        public Date? Date { get; set; }
        /// <summary>The quoteCurrencyId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QuoteCurrencyId { get; set; }
#nullable restore
#else
        public string QuoteCurrencyId { get; set; }
#endif
        /// <summary>The rate property</summary>
        public decimal? Rate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PAS.MarketData.Client.Models.UpsertCurrencyRateCommand"/> and sets the default values.
        /// </summary>
        public UpsertCurrencyRateCommand()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PAS.MarketData.Client.Models.UpsertCurrencyRateCommand"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PAS.MarketData.Client.Models.UpsertCurrencyRateCommand CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PAS.MarketData.Client.Models.UpsertCurrencyRateCommand();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "baseCurrencyId", n => { BaseCurrencyId = n.GetStringValue(); } },
                { "date", n => { Date = n.GetDateValue(); } },
                { "quoteCurrencyId", n => { QuoteCurrencyId = n.GetStringValue(); } },
                { "rate", n => { Rate = n.GetDecimalValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("baseCurrencyId", BaseCurrencyId);
            writer.WriteDateValue("date", Date);
            writer.WriteStringValue("quoteCurrencyId", QuoteCurrencyId);
            writer.WriteDecimalValue("rate", Rate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
