<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="PAS.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\PAS.Core.csproj" />
  </ItemGroup>

</Project>
