<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PAS.Policies</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="PAS.AspNetCore" />
    <Using Include="PAS.Core" />
    <Using Include="PAS.Core.Results" />
    <Using Include="PAS.Persistence.Linq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\AspireServiceDefaults\PAS.AspireServiceDefaults.csproj" />
    <ProjectReference Include="..\..\Common\AspNetCore\PAS.AspNetCore.csproj" />
    <ProjectReference Include="..\..\Common\Core\PAS.Core.csproj" />
    <ProjectReference Include="..\..\Common\Domain\PAS.Domain.csproj" />
    <ProjectReference Include="..\..\Common\Persistence\PAS.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Domain\" />
    <Folder Include="Features\" />
  </ItemGroup>

</Project>
