// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PAS.MarketData.Persistence;

#nullable disable

namespace PAS.MarketData.Persistence.Migrations
{
    [DbContext(typeof(MarketDbContext))]
    [Migration("20260916073951_V_1_0_0")]
    partial class V_1_0_0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("MarketData")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PAS.MarketData.Domain.CurrencyAggregate.Currency", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("Decimals")
                        .HasColumnType("int");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Symbol", "PAS.MarketData.Domain.CurrencyAggregate.Currency.Symbol#CurrencySymbol", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Symbol");
                        });

                    b.HasKey("Id");

                    b.ToTable("Currencies", "MarketData");
                });

            modelBuilder.Entity("PAS.MarketData.Domain.CurrencyPairAggregate.CurrencyPair", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseCurrencyId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("QuoteCurrencyId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("BaseCurrencyId");

                    b.HasIndex("QuoteCurrencyId");

                    b.ToTable("CurrencyPairs", "MarketData");
                });

            modelBuilder.Entity("PAS.MarketData.Domain.FundAggregate.Fund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("CurrencyId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(3);

                    b.Property<int>("NavDecimals")
                        .HasColumnType("int");

                    b.Property<int>("NavPricingLag")
                        .HasColumnType("int");

                    b.Property<int>("NavStalenessTolerance")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(2);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(1);

                    b.Property<int>("UnitDecimals")
                        .HasColumnType("int");

                    b.Property<string>("ValuationPeriodicity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Isin", "PAS.MarketData.Domain.FundAggregate.Fund.Isin#Isin", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("Isin")
                                .HasColumnOrder(4);
                        });

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("CurrencyId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Funds", "MarketData");
                });

            modelBuilder.Entity("PAS.Rebus.Inbox.RebusInboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("__RebusInbox", "MarketData");
                });

            modelBuilder.Entity("PAS.MarketData.Domain.CurrencyPairAggregate.CurrencyPair", b =>
                {
                    b.HasOne("PAS.MarketData.Domain.CurrencyAggregate.Currency", null)
                        .WithMany()
                        .HasForeignKey("BaseCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PAS.MarketData.Domain.CurrencyAggregate.Currency", null)
                        .WithMany()
                        .HasForeignKey("QuoteCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("PAS.MarketData.Domain.CurrencyPairAggregate.CurrencyRate", "Rates", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnOrder(0);

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<Guid>("CurrencyPairId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnOrder(1);

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<decimal>("Value")
                                .HasPrecision(28, 10)
                                .HasColumnType("decimal(28,10)");

                            b1.HasKey("Id");

                            b1.HasIndex("CurrencyPairId");

                            b1.HasIndex("Date")
                                .IsUnique();

                            b1.ToTable("CurrencyRates", "MarketData");

                            b1.WithOwner()
                                .HasForeignKey("CurrencyPairId");
                        });

                    b.Navigation("Rates");
                });

            modelBuilder.Entity("PAS.MarketData.Domain.FundAggregate.Fund", b =>
                {
                    b.HasOne("PAS.MarketData.Domain.CurrencyAggregate.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("PAS.MarketData.Domain.FundAggregate.FundNav", "Navs", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnOrder(0);

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<Guid>("FundId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnOrder(1);

                            b1.Property<decimal>("Value")
                                .HasPrecision(28, 10)
                                .HasColumnType("decimal(28,10)");

                            b1.HasKey("Id");

                            b1.HasIndex("Date")
                                .IsUnique();

                            b1.HasIndex("FundId");

                            b1.ToTable("FundNavs", "MarketData");

                            b1.WithOwner()
                                .HasForeignKey("FundId");
                        });

                    b.Navigation("Navs");
                });
#pragma warning restore 612, 618
        }
    }
}
