### Note: Some requests below require disabling API authentication/authorization.
###       Set 'Infrastructure:BypassAuthentication' to true in the AppHost's 'appsettings.Development.json'.

@Api_HostAddress = http://localhost:5136

### Healthy check
GET {{Api_HostAddress}}/health/

### Market Data API: Get fund list
GET {{Api_HostAddress}}/marketdata/funds