// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using PAS.Assets.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace PAS.Assets.Client.Currencies.Rates
{
    /// <summary>
    /// Builds and executes requests for operations under \currencies\rates
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RatesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::PAS.Assets.Client.Currencies.Rates.RatesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RatesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/currencies/rates{?baseCurrencyId*,pageNumber*,pageSize*,quoteCurrencyId*,startDate*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PAS.Assets.Client.Currencies.Rates.RatesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RatesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/currencies/rates{?baseCurrencyId*,pageNumber*,pageSize*,quoteCurrencyId*,startDate*}", rawUrl)
        {
        }
        /// <summary>
        /// Get a paginated list of currency exchange rates.
        /// </summary>
        /// <returns>A <see cref="global::PAS.Assets.Client.Models.GetCurrencyExchangeRateListResult"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::PAS.Assets.Client.Models.ValidationProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::PAS.Assets.Client.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::PAS.Assets.Client.Models.GetCurrencyExchangeRateListResult?> GetAsync(Action<RequestConfiguration<global::PAS.Assets.Client.Currencies.Rates.RatesRequestBuilder.RatesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::PAS.Assets.Client.Models.GetCurrencyExchangeRateListResult> GetAsync(Action<RequestConfiguration<global::PAS.Assets.Client.Currencies.Rates.RatesRequestBuilder.RatesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::PAS.Assets.Client.Models.ValidationProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::PAS.Assets.Client.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::PAS.Assets.Client.Models.GetCurrencyExchangeRateListResult>(requestInfo, global::PAS.Assets.Client.Models.GetCurrencyExchangeRateListResult.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Add or update a currency exchange rate.
        /// </summary>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::PAS.Assets.Client.Models.ValidationProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::PAS.Assets.Client.Models.ProblemDetails">When receiving a 404 status code</exception>
        /// <exception cref="global::PAS.Assets.Client.Models.ProblemDetails">When receiving a 422 status code</exception>
        /// <exception cref="global::PAS.Assets.Client.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PostAsync(global::PAS.Assets.Client.Models.UpsertCurrencyExchangeRateCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PostAsync(global::PAS.Assets.Client.Models.UpsertCurrencyExchangeRateCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::PAS.Assets.Client.Models.ValidationProblemDetails.CreateFromDiscriminatorValue },
                { "404", global::PAS.Assets.Client.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "422", global::PAS.Assets.Client.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::PAS.Assets.Client.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a paginated list of currency exchange rates.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::PAS.Assets.Client.Currencies.Rates.RatesRequestBuilder.RatesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::PAS.Assets.Client.Currencies.Rates.RatesRequestBuilder.RatesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Add or update a currency exchange rate.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::PAS.Assets.Client.Models.UpsertCurrencyExchangeRateCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::PAS.Assets.Client.Models.UpsertCurrencyExchangeRateCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/problem+json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::PAS.Assets.Client.Currencies.Rates.RatesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::PAS.Assets.Client.Currencies.Rates.RatesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::PAS.Assets.Client.Currencies.Rates.RatesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get a paginated list of currency exchange rates.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RatesRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("baseCurrencyId")]
            public string? BaseCurrencyId { get; set; }
#nullable restore
#else
            [QueryParameter("baseCurrencyId")]
            public string BaseCurrencyId { get; set; }
#endif
            [QueryParameter("pageNumber")]
            public int? PageNumber { get; set; }
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("quoteCurrencyId")]
            public string? QuoteCurrencyId { get; set; }
#nullable restore
#else
            [QueryParameter("quoteCurrencyId")]
            public string QuoteCurrencyId { get; set; }
#endif
            [QueryParameter("startDate")]
            public Date? StartDate { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RatesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::PAS.Assets.Client.Currencies.Rates.RatesRequestBuilder.RatesRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RatesRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
