// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PAS.Assets.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateCollectiveFundCommand : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The currency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The isin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Isin { get; set; }
#nullable restore
#else
        public string Isin { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The nav property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PAS.Assets.Client.Models.CreateCollectiveFundCommand.CreateCollectiveFundCommand_nav? Nav { get; set; }
#nullable restore
#else
        public global::PAS.Assets.Client.Models.CreateCollectiveFundCommand.CreateCollectiveFundCommand_nav Nav { get; set; }
#endif
        /// <summary>The valuationPeriodicity property</summary>
        public global::PAS.Assets.Client.Models.FundValuationPeriodicity? ValuationPeriodicity { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PAS.Assets.Client.Models.CreateCollectiveFundCommand"/> and sets the default values.
        /// </summary>
        public CreateCollectiveFundCommand()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PAS.Assets.Client.Models.CreateCollectiveFundCommand"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PAS.Assets.Client.Models.CreateCollectiveFundCommand CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PAS.Assets.Client.Models.CreateCollectiveFundCommand();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "isin", n => { Isin = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "nav", n => { Nav = n.GetObjectValue<global::PAS.Assets.Client.Models.CreateCollectiveFundCommand.CreateCollectiveFundCommand_nav>(global::PAS.Assets.Client.Models.CreateCollectiveFundCommand.CreateCollectiveFundCommand_nav.CreateFromDiscriminatorValue); } },
                { "valuationPeriodicity", n => { ValuationPeriodicity = n.GetEnumValue<global::PAS.Assets.Client.Models.FundValuationPeriodicity>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("currency", Currency);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("isin", Isin);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::PAS.Assets.Client.Models.CreateCollectiveFundCommand.CreateCollectiveFundCommand_nav>("nav", Nav);
            writer.WriteEnumValue<global::PAS.Assets.Client.Models.FundValuationPeriodicity>("valuationPeriodicity", ValuationPeriodicity);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::PAS.Assets.Client.Models.CreateCollectiveFundCommandFundNav"/>, <see cref="global::PAS.Assets.Client.Models.CreateCollectiveFundCommand_navMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CreateCollectiveFundCommand_nav : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::PAS.Assets.Client.Models.CreateCollectiveFundCommandFundNav"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PAS.Assets.Client.Models.CreateCollectiveFundCommandFundNav? CreateCollectiveFundCommandFundNav { get; set; }
#nullable restore
#else
            public global::PAS.Assets.Client.Models.CreateCollectiveFundCommandFundNav CreateCollectiveFundCommandFundNav { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PAS.Assets.Client.Models.CreateCollectiveFundCommand_navMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PAS.Assets.Client.Models.CreateCollectiveFundCommand_navMember1? CreateCollectiveFundCommandNavMember1 { get; set; }
#nullable restore
#else
            public global::PAS.Assets.Client.Models.CreateCollectiveFundCommand_navMember1 CreateCollectiveFundCommandNavMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::PAS.Assets.Client.Models.CreateCollectiveFundCommand.CreateCollectiveFundCommand_nav"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::PAS.Assets.Client.Models.CreateCollectiveFundCommand.CreateCollectiveFundCommand_nav CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::PAS.Assets.Client.Models.CreateCollectiveFundCommand.CreateCollectiveFundCommand_nav();
                if("CreateCollectiveFundCommandFundNav".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CreateCollectiveFundCommandFundNav = new global::PAS.Assets.Client.Models.CreateCollectiveFundCommandFundNav();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CreateCollectiveFundCommandFundNav != null)
                {
                    return CreateCollectiveFundCommandFundNav.GetFieldDeserializers();
                }
                else if(CreateCollectiveFundCommandNavMember1 != null)
                {
                    return CreateCollectiveFundCommandNavMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CreateCollectiveFundCommandFundNav != null)
                {
                    writer.WriteObjectValue<global::PAS.Assets.Client.Models.CreateCollectiveFundCommandFundNav>(null, CreateCollectiveFundCommandFundNav);
                }
                else if(CreateCollectiveFundCommandNavMember1 != null)
                {
                    writer.WriteObjectValue<global::PAS.Assets.Client.Models.CreateCollectiveFundCommand_navMember1>(null, CreateCollectiveFundCommandNavMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
