// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PAS.ActuarialEngine.Persistence;

#nullable disable

namespace PAS.ActuarialEngine.Persistence.Migrations
{
    [DbContext(typeof(ActuDbContext))]
    [Migration("20260911103425_V_1_0_0")]
    partial class V_1_0_0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Actu")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PAS.ActuarialEngine.Domain.PolicyAggregate.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsSealed")
                        .HasColumnType("bit");

                    b.Property<long?>("LastHandledRetroactiveChangeId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("LatestEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WarningMessage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("LastHandledRetroactiveChangeId");

                    b.HasIndex("LatestEventId");

                    b.ToTable("Policies", "Actu");
                });

            modelBuilder.Entity("PAS.ActuarialEngine.Domain.PolicyAggregate.RetroactiveChange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("RetroactiveChanges", "Actu");
                });

            modelBuilder.Entity("PAS.ActuarialEngine.Domain.PolicyAggregate.ValuationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Seq")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId", "Date", "OperationId")
                        .IsUnique()
                        .HasFilter("[OperationId] IS NOT NULL");

                    b.ToTable("ValuationEvents", "Actu");
                });

            modelBuilder.Entity("PAS.Rebus.Inbox.RebusInboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("__RebusInbox", "Actu");
                });

            modelBuilder.Entity("PAS.ActuarialEngine.Domain.PolicyAggregate.Policy", b =>
                {
                    b.HasOne("PAS.ActuarialEngine.Domain.PolicyAggregate.RetroactiveChange", null)
                        .WithMany()
                        .HasForeignKey("LastHandledRetroactiveChangeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PAS.ActuarialEngine.Domain.PolicyAggregate.ValuationEvent", null)
                        .WithMany()
                        .HasForeignKey("LatestEventId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PAS.ActuarialEngine.Domain.PolicyAggregate.ValuationEvent", b =>
                {
                    b.HasOne("PAS.ActuarialEngine.Domain.PolicyAggregate.Policy", null)
                        .WithMany("Events")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("PAS.ActuarialEngine.Domain.PolicyAggregate.MathReserve", "MathReserves", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnOrder(0);

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<Guid>("FundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Units")
                                .HasPrecision(28, 10)
                                .HasColumnType("decimal(28,10)");

                            b1.Property<Guid>("ValuationEventId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnOrder(1);

                            b1.HasKey("Id");

                            b1.HasIndex("ValuationEventId");

                            b1.ToTable("MathReserves", "Actu");

                            b1.WithOwner()
                                .HasForeignKey("ValuationEventId");

                            b1.OwnsOne("PAS.ActuarialEngine.Domain.PolicyAggregate.ValuationPricing", "Pricing", b2 =>
                                {
                                    b2.Property<long>("MathReserveId")
                                        .HasColumnType("bigint");

                                    b2.Property<decimal>("AmountInEur")
                                        .HasPrecision(28, 10)
                                        .HasColumnType("decimal(28,10)")
                                        .HasColumnName("AmountInEur");

                                    b2.Property<decimal>("AmountInFundCurrency")
                                        .HasPrecision(28, 10)
                                        .HasColumnType("decimal(28,10)")
                                        .HasColumnName("AmountInFundCurrency");

                                    b2.Property<decimal>("AmountInPolicyCurrency")
                                        .HasPrecision(28, 10)
                                        .HasColumnType("decimal(28,10)")
                                        .HasColumnName("AmountInPolicyCurrency");

                                    b2.HasKey("MathReserveId");

                                    b2.ToTable("MathReserves", "Actu");

                                    b2.WithOwner()
                                        .HasForeignKey("MathReserveId");

                                    b2.OwnsOne("PAS.ActuarialEngine.Domain.PolicyAggregate.FxRate", "FundToPolicyFxRate", b3 =>
                                        {
                                            b3.Property<long>("ValuationPricingMathReserveId")
                                                .HasColumnType("bigint");

                                            b3.Property<DateOnly>("Date")
                                                .HasColumnType("date")
                                                .HasColumnName("FundToPolicyFxRateDate");

                                            b3.Property<decimal>("Value")
                                                .HasPrecision(28, 10)
                                                .HasColumnType("decimal(28,10)")
                                                .HasColumnName("FundToPolicyFxRateValue");

                                            b3.HasKey("ValuationPricingMathReserveId");

                                            b3.ToTable("MathReserves", "Actu");

                                            b3.WithOwner()
                                                .HasForeignKey("ValuationPricingMathReserveId");
                                        });

                                    b2.OwnsOne("PAS.ActuarialEngine.Domain.PolicyAggregate.FundNav", "Nav", b3 =>
                                        {
                                            b3.Property<long>("ValuationPricingMathReserveId")
                                                .HasColumnType("bigint");

                                            b3.Property<DateOnly>("Date")
                                                .HasColumnType("date")
                                                .HasColumnName("NavDate");

                                            b3.Property<decimal>("Value")
                                                .HasPrecision(28, 10)
                                                .HasColumnType("decimal(28,10)")
                                                .HasColumnName("NavValue");

                                            b3.HasKey("ValuationPricingMathReserveId");

                                            b3.ToTable("MathReserves", "Actu");

                                            b3.WithOwner()
                                                .HasForeignKey("ValuationPricingMathReserveId");
                                        });

                                    b2.OwnsOne("PAS.ActuarialEngine.Domain.PolicyAggregate.FxRate", "PolicyToEurFxRate", b3 =>
                                        {
                                            b3.Property<long>("ValuationPricingMathReserveId")
                                                .HasColumnType("bigint");

                                            b3.Property<DateOnly>("Date")
                                                .HasColumnType("date")
                                                .HasColumnName("PolicyToEurFxRateDate");

                                            b3.Property<decimal>("Value")
                                                .HasPrecision(28, 10)
                                                .HasColumnType("decimal(28,10)")
                                                .HasColumnName("PolicyToEurFxRateValue");

                                            b3.HasKey("ValuationPricingMathReserveId");

                                            b3.ToTable("MathReserves", "Actu");

                                            b3.WithOwner()
                                                .HasForeignKey("ValuationPricingMathReserveId");
                                        });

                                    b2.OwnsOne("PAS.ActuarialEngine.Domain.PolicyAggregate.FxRate", "PolicyToFundFxRate", b3 =>
                                        {
                                            b3.Property<long>("ValuationPricingMathReserveId")
                                                .HasColumnType("bigint");

                                            b3.Property<DateOnly>("Date")
                                                .HasColumnType("date")
                                                .HasColumnName("PolicyToFundFxRateDate");

                                            b3.Property<decimal>("Value")
                                                .HasPrecision(28, 10)
                                                .HasColumnType("decimal(28,10)")
                                                .HasColumnName("PolicyToFundFxRateValue");

                                            b3.HasKey("ValuationPricingMathReserveId");

                                            b3.ToTable("MathReserves", "Actu");

                                            b3.WithOwner()
                                                .HasForeignKey("ValuationPricingMathReserveId");
                                        });

                                    b2.Navigation("FundToPolicyFxRate");

                                    b2.Navigation("Nav")
                                        .IsRequired();

                                    b2.Navigation("PolicyToEurFxRate");

                                    b2.Navigation("PolicyToFundFxRate");
                                });

                            b1.Navigation("Pricing")
                                .IsRequired();
                        });

                    b.OwnsMany("PAS.ActuarialEngine.Domain.PolicyAggregate.ValuationMovement", "Movements", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnOrder(0);

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<Guid>("FundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<decimal>("Units")
                                .HasPrecision(28, 10)
                                .HasColumnType("decimal(28,10)");

                            b1.Property<Guid>("ValuationEventId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnOrder(1);

                            b1.HasKey("Id");

                            b1.HasIndex("ValuationEventId");

                            b1.ToTable("ValuationMovements", "Actu");

                            b1.WithOwner()
                                .HasForeignKey("ValuationEventId");

                            b1.OwnsOne("PAS.ActuarialEngine.Domain.PolicyAggregate.ValuationPricing", "Pricing", b2 =>
                                {
                                    b2.Property<long>("ValuationMovementId")
                                        .HasColumnType("bigint");

                                    b2.Property<decimal>("AmountInEur")
                                        .HasPrecision(28, 10)
                                        .HasColumnType("decimal(28,10)")
                                        .HasColumnName("AmountInEur");

                                    b2.Property<decimal>("AmountInFundCurrency")
                                        .HasPrecision(28, 10)
                                        .HasColumnType("decimal(28,10)")
                                        .HasColumnName("AmountInFundCurrency");

                                    b2.Property<decimal>("AmountInPolicyCurrency")
                                        .HasPrecision(28, 10)
                                        .HasColumnType("decimal(28,10)")
                                        .HasColumnName("AmountInPolicyCurrency");

                                    b2.Property<string>("NavValuationMode")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("NavValuationMode");

                                    b2.HasKey("ValuationMovementId");

                                    b2.ToTable("ValuationMovements", "Actu");

                                    b2.WithOwner()
                                        .HasForeignKey("ValuationMovementId");

                                    b2.OwnsOne("PAS.ActuarialEngine.Domain.PolicyAggregate.FxRate", "FundToPolicyFxRate", b3 =>
                                        {
                                            b3.Property<long>("ValuationPricingValuationMovementId")
                                                .HasColumnType("bigint");

                                            b3.Property<DateOnly>("Date")
                                                .HasColumnType("date")
                                                .HasColumnName("FundToPolicyFxRateDate");

                                            b3.Property<decimal>("Value")
                                                .HasPrecision(28, 10)
                                                .HasColumnType("decimal(28,10)")
                                                .HasColumnName("FundToPolicyFxRateValue");

                                            b3.HasKey("ValuationPricingValuationMovementId");

                                            b3.ToTable("ValuationMovements", "Actu");

                                            b3.WithOwner()
                                                .HasForeignKey("ValuationPricingValuationMovementId");
                                        });

                                    b2.OwnsOne("PAS.ActuarialEngine.Domain.PolicyAggregate.FundNav", "Nav", b3 =>
                                        {
                                            b3.Property<long>("ValuationPricingValuationMovementId")
                                                .HasColumnType("bigint");

                                            b3.Property<DateOnly>("Date")
                                                .HasColumnType("date")
                                                .HasColumnName("NavDate");

                                            b3.Property<decimal>("Value")
                                                .HasPrecision(28, 10)
                                                .HasColumnType("decimal(28,10)")
                                                .HasColumnName("NavValue");

                                            b3.HasKey("ValuationPricingValuationMovementId");

                                            b3.ToTable("ValuationMovements", "Actu");

                                            b3.WithOwner()
                                                .HasForeignKey("ValuationPricingValuationMovementId");
                                        });

                                    b2.OwnsOne("PAS.ActuarialEngine.Domain.PolicyAggregate.FxRate", "PolicyToEurFxRate", b3 =>
                                        {
                                            b3.Property<long>("ValuationPricingValuationMovementId")
                                                .HasColumnType("bigint");

                                            b3.Property<DateOnly>("Date")
                                                .HasColumnType("date")
                                                .HasColumnName("PolicyToEurFxRateDate");

                                            b3.Property<decimal>("Value")
                                                .HasPrecision(28, 10)
                                                .HasColumnType("decimal(28,10)")
                                                .HasColumnName("PolicyToEurFxRateValue");

                                            b3.HasKey("ValuationPricingValuationMovementId");

                                            b3.ToTable("ValuationMovements", "Actu");

                                            b3.WithOwner()
                                                .HasForeignKey("ValuationPricingValuationMovementId");
                                        });

                                    b2.OwnsOne("PAS.ActuarialEngine.Domain.PolicyAggregate.FxRate", "PolicyToFundFxRate", b3 =>
                                        {
                                            b3.Property<long>("ValuationPricingValuationMovementId")
                                                .HasColumnType("bigint");

                                            b3.Property<DateOnly>("Date")
                                                .HasColumnType("date")
                                                .HasColumnName("PolicyToFundFxRateDate");

                                            b3.Property<decimal>("Value")
                                                .HasPrecision(28, 10)
                                                .HasColumnType("decimal(28,10)")
                                                .HasColumnName("PolicyToFundFxRateValue");

                                            b3.HasKey("ValuationPricingValuationMovementId");

                                            b3.ToTable("ValuationMovements", "Actu");

                                            b3.WithOwner()
                                                .HasForeignKey("ValuationPricingValuationMovementId");
                                        });

                                    b2.Navigation("FundToPolicyFxRate");

                                    b2.Navigation("Nav")
                                        .IsRequired();

                                    b2.Navigation("PolicyToEurFxRate");

                                    b2.Navigation("PolicyToFundFxRate");
                                });

                            b1.Navigation("Pricing")
                                .IsRequired();
                        });

                    b.Navigation("MathReserves");

                    b.Navigation("Movements");
                });

            modelBuilder.Entity("PAS.ActuarialEngine.Domain.PolicyAggregate.Policy", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
