// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using PAS.MarketData.Client.Funds.Collective;
using PAS.MarketData.Client.Funds.Dedicated;
using PAS.MarketData.Client.Funds.Item;
using PAS.MarketData.Client.Funds.Search;
using PAS.MarketData.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace PAS.MarketData.Client.Funds
{
    /// <summary>
    /// Builds and executes requests for operations under \funds
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FundsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The collective property</summary>
        public global::PAS.MarketData.Client.Funds.Collective.CollectiveRequestBuilder Collective
        {
            get => new global::PAS.MarketData.Client.Funds.Collective.CollectiveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dedicated property</summary>
        public global::PAS.MarketData.Client.Funds.Dedicated.DedicatedRequestBuilder Dedicated
        {
            get => new global::PAS.MarketData.Client.Funds.Dedicated.DedicatedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::PAS.MarketData.Client.Funds.Search.SearchRequestBuilder Search
        {
            get => new global::PAS.MarketData.Client.Funds.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the PAS.MarketData.Client.funds.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::PAS.MarketData.Client.Funds.Item.FundsItemRequestBuilder"/></returns>
        public global::PAS.MarketData.Client.Funds.Item.FundsItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::PAS.MarketData.Client.Funds.Item.FundsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the PAS.MarketData.Client.funds.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::PAS.MarketData.Client.Funds.Item.FundsItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::PAS.MarketData.Client.Funds.Item.FundsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::PAS.MarketData.Client.Funds.Item.FundsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PAS.MarketData.Client.Funds.FundsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FundsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/funds{?pageNumber*,pageSize*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PAS.MarketData.Client.Funds.FundsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FundsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/funds{?pageNumber*,pageSize*}", rawUrl)
        {
        }
        /// <summary>
        /// Get a paginated list of funds.
        /// </summary>
        /// <returns>A <see cref="global::PAS.MarketData.Client.Models.SearchFundsResult"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::PAS.MarketData.Client.Models.ValidationProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::PAS.MarketData.Client.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::PAS.MarketData.Client.Models.SearchFundsResult?> GetAsync(Action<RequestConfiguration<global::PAS.MarketData.Client.Funds.FundsRequestBuilder.FundsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::PAS.MarketData.Client.Models.SearchFundsResult> GetAsync(Action<RequestConfiguration<global::PAS.MarketData.Client.Funds.FundsRequestBuilder.FundsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::PAS.MarketData.Client.Models.ValidationProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::PAS.MarketData.Client.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::PAS.MarketData.Client.Models.SearchFundsResult>(requestInfo, global::PAS.MarketData.Client.Models.SearchFundsResult.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a paginated list of funds.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::PAS.MarketData.Client.Funds.FundsRequestBuilder.FundsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::PAS.MarketData.Client.Funds.FundsRequestBuilder.FundsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::PAS.MarketData.Client.Funds.FundsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::PAS.MarketData.Client.Funds.FundsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::PAS.MarketData.Client.Funds.FundsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get a paginated list of funds.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FundsRequestBuilderGetQueryParameters 
        {
            [QueryParameter("pageNumber")]
            public int? PageNumber { get; set; }
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FundsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::PAS.MarketData.Client.Funds.FundsRequestBuilder.FundsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
