// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PAS.PolicyValuation.Persistence.Write;

#nullable disable

namespace PAS.PolicyValuation.Persistence.Write.Migrations
{
    [DbContext(typeof(ValuationDbContext))]
    [Migration("20261006083209_V_1_0_0")]
    partial class V_1_0_0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("PolicyValuation")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PAS.PolicyValuation.Domain.RetroactiveChangeAggregate.RetroactiveChange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("RetroactiveChanges", "PolicyValuation");
                });

            modelBuilder.Entity("PAS.PolicyValuation.Domain.ValuationLedgerAggregate.ValuationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<long>("LedgerId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalReservesInEur")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalReservesInPolicyCurrency")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("LedgerId", "Date", "OperationId")
                        .IsUnique()
                        .HasFilter("[OperationId] IS NOT NULL");

                    b.ToTable("ValuationEvents", "PolicyValuation");
                });

            modelBuilder.Entity("PAS.PolicyValuation.Domain.ValuationLedgerAggregate.ValuationLedger", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrencyId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsSealed")
                        .HasColumnType("bit");

                    b.Property<long?>("LastHandledRetroactiveChangeId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("LatestEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WarningMessage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LastHandledRetroactiveChangeId");

                    b.HasIndex("LatestEventId");

                    b.ToTable("ValuationLedgers", "PolicyValuation");
                });

            modelBuilder.Entity("PAS.Rebus.Inbox.RebusInboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("__RebusInbox", "PolicyValuation");
                });

            modelBuilder.Entity("PAS.PolicyValuation.Domain.ValuationLedgerAggregate.ValuationEvent", b =>
                {
                    b.HasOne("PAS.PolicyValuation.Domain.ValuationLedgerAggregate.ValuationLedger", null)
                        .WithMany("Events")
                        .HasForeignKey("LedgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("PAS.PolicyValuation.Domain.ValuationLedgerAggregate.Movement", "Movements", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnOrder(0);

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("Details")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("EventId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnOrder(1);

                            b1.Property<Guid>("FundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("Units")
                                .HasPrecision(28, 10)
                                .HasColumnType("decimal(28,10)")
                                .HasColumnName("Units");

                            b1.HasKey("Id");

                            b1.HasIndex("EventId");

                            b1.ToTable("Movements", "PolicyValuation");

                            b1.WithOwner()
                                .HasForeignKey("EventId");

                            b1.OwnsOne("PAS.PolicyValuation.Domain.ValuationLedgerAggregate.MovementAmount", "Amount", b2 =>
                                {
                                    b2.Property<long>("MovementId")
                                        .HasColumnType("bigint");

                                    b2.Property<decimal>("InEur")
                                        .HasPrecision(14, 4)
                                        .HasColumnType("decimal(14,4)")
                                        .HasColumnName("AmountInEur");

                                    b2.Property<decimal>("InFundCurrency")
                                        .HasPrecision(14, 4)
                                        .HasColumnType("decimal(14,4)")
                                        .HasColumnName("Amount");

                                    b2.Property<decimal>("InPolicyCurrency")
                                        .HasPrecision(14, 4)
                                        .HasColumnType("decimal(14,4)")
                                        .HasColumnName("AmountInPolicyCurrency");

                                    b2.HasKey("MovementId");

                                    b2.ToTable("Movements", "PolicyValuation");

                                    b2.WithOwner()
                                        .HasForeignKey("MovementId");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();
                        });

                    b.OwnsMany("PAS.PolicyValuation.Domain.ValuationLedgerAggregate.Reserve", "Reserves", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnOrder(0);

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("Details")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("EventId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnOrder(1);

                            b1.Property<Guid>("FundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Units")
                                .HasPrecision(28, 10)
                                .HasColumnType("decimal(28,10)")
                                .HasColumnName("Units");

                            b1.HasKey("Id");

                            b1.HasIndex("EventId");

                            b1.ToTable("Reserves", "PolicyValuation");

                            b1.WithOwner()
                                .HasForeignKey("EventId");

                            b1.OwnsOne("PAS.PolicyValuation.Domain.ValuationLedgerAggregate.ReserveAmount", "Amount", b2 =>
                                {
                                    b2.Property<long>("ReserveId")
                                        .HasColumnType("bigint");

                                    b2.Property<decimal>("InEur")
                                        .HasPrecision(14, 4)
                                        .HasColumnType("decimal(14,4)")
                                        .HasColumnName("AmountInEur");

                                    b2.Property<decimal>("InFundCurrency")
                                        .HasPrecision(14, 4)
                                        .HasColumnType("decimal(14,4)")
                                        .HasColumnName("Amount");

                                    b2.Property<decimal>("InPolicyCurrency")
                                        .HasPrecision(14, 4)
                                        .HasColumnType("decimal(14,4)")
                                        .HasColumnName("AmountInPolicyCurrency");

                                    b2.HasKey("ReserveId");

                                    b2.ToTable("Reserves", "PolicyValuation");

                                    b2.WithOwner()
                                        .HasForeignKey("ReserveId");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();
                        });

                    b.Navigation("Movements");

                    b.Navigation("Reserves");
                });

            modelBuilder.Entity("PAS.PolicyValuation.Domain.ValuationLedgerAggregate.ValuationLedger", b =>
                {
                    b.HasOne("PAS.PolicyValuation.Domain.RetroactiveChangeAggregate.RetroactiveChange", null)
                        .WithMany()
                        .HasForeignKey("LastHandledRetroactiveChangeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PAS.PolicyValuation.Domain.ValuationLedgerAggregate.ValuationEvent", null)
                        .WithMany()
                        .HasForeignKey("LatestEventId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PAS.PolicyValuation.Domain.ValuationLedgerAggregate.ValuationLedger", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
