// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PAS.Assets.Persistence;

#nullable disable

namespace PAS.Assets.Persistence.Migrations
{
    [DbContext(typeof(AssetDbContext))]
    [Migration("20260814094306_V_1_0_0")]
    partial class V_1_0_0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Asset")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("FundNavSeq")
                .IncrementsBy(10);

            modelBuilder.Entity("PAS.Assets.Domain.CurrencyAggregate.Currency", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Symbol", "PAS.Assets.Domain.CurrencyAggregate.Currency.Symbol#CurrencySymbol", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Symbol");
                        });

                    b.HasKey("Id");

                    b.ToTable("Currencies", "Asset");
                });

            modelBuilder.Entity("PAS.Assets.Domain.FundAggregate.Fund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Isin", "PAS.Assets.Domain.FundAggregate.Fund.Isin#Isin", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("Isin");
                        });

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("CurrencyId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Funds", "Asset");
                });

            modelBuilder.Entity("PAS.Persistence.Rebus.RebusInboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("__RebusInbox", "Asset");
                });

            modelBuilder.Entity("PAS.Assets.Domain.FundAggregate.Fund", b =>
                {
                    b.HasOne("PAS.Assets.Domain.CurrencyAggregate.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("PAS.Assets.Domain.FundAggregate.FundNav", "Navs", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseHiLo(b1.Property<long>("Id"), "FundNavSeq");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("FundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Value")
                                .HasColumnType("float");

                            b1.HasKey("Id");

                            b1.HasIndex("Date")
                                .IsUnique();

                            b1.HasIndex("FundId");

                            b1.ToTable("FundNavs", "Asset");

                            b1.WithOwner()
                                .HasForeignKey("FundId");
                        });

                    b.Navigation("Navs");
                });
#pragma warning restore 612, 618
        }
    }
}
