// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PAS.Policies.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetPolicyResultOperationFullSurrender_Type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "FullSurrender")]
        #pragma warning disable CS1591
        FullSurrender,
        #pragma warning restore CS1591
    }
}
