// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace PAS.Policies.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetPolicyResult : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The currencyId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyId { get; set; }
#nullable restore
#else
        public string CurrencyId { get; set; }
#endif
        /// <summary>The effectiveDate property</summary>
        public Date? EffectiveDate { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The operations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::PAS.Policies.Client.Models.GetPolicyResultOperation>? Operations { get; set; }
#nullable restore
#else
        public List<global::PAS.Policies.Client.Models.GetPolicyResultOperation> Operations { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::PAS.Policies.Client.Models.PolicyStatus? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PAS.Policies.Client.Models.GetPolicyResult"/> and sets the default values.
        /// </summary>
        public GetPolicyResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PAS.Policies.Client.Models.GetPolicyResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PAS.Policies.Client.Models.GetPolicyResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PAS.Policies.Client.Models.GetPolicyResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currencyId", n => { CurrencyId = n.GetStringValue(); } },
                { "effectiveDate", n => { EffectiveDate = n.GetDateValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "operations", n => { Operations = n.GetCollectionOfObjectValues<global::PAS.Policies.Client.Models.GetPolicyResultOperation>(global::PAS.Policies.Client.Models.GetPolicyResultOperation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status", n => { Status = n.GetEnumValue<global::PAS.Policies.Client.Models.PolicyStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("currencyId", CurrencyId);
            writer.WriteDateValue("effectiveDate", EffectiveDate);
            writer.WriteGuidValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::PAS.Policies.Client.Models.GetPolicyResultOperation>("operations", Operations);
            writer.WriteEnumValue<global::PAS.Policies.Client.Models.PolicyStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
