// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PAS.Policies.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PolicyStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "Issued")]
        #pragma warning disable CS1591
        Issued,
        #pragma warning restore CS1591
    }
}
