// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PAS.PolicyValuation.Persistence.Write;

#nullable disable

namespace PAS.PolicyValuation.Persistence.Write.Migrations
{
    [DbContext(typeof(ValuationDbContext))]
    partial class PolicyValuationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("PolicyValuation")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PAS.PolicyValuation.Domain.PolicyAggregate.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrencyId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsSealed")
                        .HasColumnType("bit");

                    b.Property<long?>("LastHandledRetroactiveChangeId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("LatestValuationEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WarningMessage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("LastHandledRetroactiveChangeId");

                    b.HasIndex("LatestValuationEventId");

                    b.ToTable("Policies", "PolicyValuation");
                });

            modelBuilder.Entity("PAS.PolicyValuation.Domain.PolicyAggregate.RetroactiveChange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("RetroactiveChanges", "PolicyValuation");
                });

            modelBuilder.Entity("PAS.PolicyValuation.Domain.PolicyAggregate.ValuationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyValuationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Seq")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalReservesInEur")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalReservesInPolicyCurrency")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyValuationId", "Date", "OperationId")
                        .IsUnique()
                        .HasFilter("[OperationId] IS NOT NULL");

                    b.ToTable("ValuationEvents", "PolicyValuation");
                });

            modelBuilder.Entity("PAS.Rebus.Inbox.RebusInboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("__RebusInbox", "PolicyValuation");
                });

            modelBuilder.Entity("PAS.PolicyValuation.Domain.PolicyAggregate.Policy", b =>
                {
                    b.HasOne("PAS.PolicyValuation.Domain.PolicyAggregate.RetroactiveChange", null)
                        .WithMany()
                        .HasForeignKey("LastHandledRetroactiveChangeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PAS.PolicyValuation.Domain.PolicyAggregate.ValuationEvent", null)
                        .WithMany()
                        .HasForeignKey("LatestValuationEventId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PAS.PolicyValuation.Domain.PolicyAggregate.ValuationEvent", b =>
                {
                    b.HasOne("PAS.PolicyValuation.Domain.PolicyAggregate.Policy", null)
                        .WithMany("Events")
                        .HasForeignKey("PolicyValuationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("PAS.PolicyValuation.Domain.PolicyAggregate.ValuationMovement", "Movements", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnOrder(0);

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<Guid>("FundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("ValuationEventId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnOrder(1);

                            b1.HasKey("Id");

                            b1.HasIndex("ValuationEventId");

                            b1.ToTable("ValuationMovements", "PolicyValuation");

                            b1.WithOwner()
                                .HasForeignKey("ValuationEventId");

                            b1.OwnsOne("PAS.PolicyValuation.Domain.PolicyAggregate.FundValuationDetails", "Valuation", b2 =>
                                {
                                    b2.Property<long>("ValuationMovementId")
                                        .HasColumnType("bigint");

                                    b2.Property<decimal>("AmountInEur")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("AmountInEur");

                                    b2.Property<decimal>("AmountInFundCurrency")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("AmountInFundCurrency");

                                    b2.Property<decimal>("AmountInPolicyCurrency")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("AmountInPolicyCurrency");

                                    b2.Property<string>("NavValuationMode")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("nvarchar(128)")
                                        .HasColumnName("NavValuationMode");

                                    b2.Property<decimal>("RawAmountInEur")
                                        .HasPrecision(28, 10)
                                        .HasColumnType("decimal(28,10)")
                                        .HasColumnName("RawAmountInEur");

                                    b2.Property<decimal>("RawAmountInFundCurrency")
                                        .HasPrecision(28, 10)
                                        .HasColumnType("decimal(28,10)")
                                        .HasColumnName("RawAmountInFundCurrency");

                                    b2.Property<decimal>("RawAmountInPolicyCurrency")
                                        .HasPrecision(28, 10)
                                        .HasColumnType("decimal(28,10)")
                                        .HasColumnName("RawAmountInPolicyCurrency");

                                    b2.Property<decimal>("Units")
                                        .HasPrecision(28, 10)
                                        .HasColumnType("decimal(28,10)")
                                        .HasColumnName("Units");

                                    b2.HasKey("ValuationMovementId");

                                    b2.ToTable("ValuationMovements", "PolicyValuation");

                                    b2.WithOwner()
                                        .HasForeignKey("ValuationMovementId");

                                    b2.OwnsOne("PAS.PolicyValuation.Domain.PolicyAggregate.CurrencyRate", "FundToPolicyFxRate", b3 =>
                                        {
                                            b3.Property<long>("FundValuationDetailsValuationMovementId")
                                                .HasColumnType("bigint");

                                            b3.Property<DateOnly>("Date")
                                                .HasColumnType("date")
                                                .HasColumnName("FundToPolicyFxRateDate");

                                            b3.Property<decimal>("Value")
                                                .HasPrecision(28, 10)
                                                .HasColumnType("decimal(28,10)")
                                                .HasColumnName("FundToPolicyFxRateValue");

                                            b3.HasKey("FundValuationDetailsValuationMovementId");

                                            b3.ToTable("ValuationMovements", "PolicyValuation");

                                            b3.WithOwner()
                                                .HasForeignKey("FundValuationDetailsValuationMovementId");
                                        });

                                    b2.OwnsOne("PAS.PolicyValuation.Domain.PolicyAggregate.FundNav", "Nav", b3 =>
                                        {
                                            b3.Property<long>("FundValuationDetailsValuationMovementId")
                                                .HasColumnType("bigint");

                                            b3.Property<DateOnly>("Date")
                                                .HasColumnType("date")
                                                .HasColumnName("NavDate");

                                            b3.Property<decimal>("Value")
                                                .HasPrecision(28, 10)
                                                .HasColumnType("decimal(28,10)")
                                                .HasColumnName("NavValue");

                                            b3.HasKey("FundValuationDetailsValuationMovementId");

                                            b3.ToTable("ValuationMovements", "PolicyValuation");

                                            b3.WithOwner()
                                                .HasForeignKey("FundValuationDetailsValuationMovementId");
                                        });

                                    b2.OwnsOne("PAS.PolicyValuation.Domain.PolicyAggregate.CurrencyRate", "PolicyToEurFxRate", b3 =>
                                        {
                                            b3.Property<long>("FundValuationDetailsValuationMovementId")
                                                .HasColumnType("bigint");

                                            b3.Property<DateOnly>("Date")
                                                .HasColumnType("date")
                                                .HasColumnName("PolicyToEurFxRateDate");

                                            b3.Property<decimal>("Value")
                                                .HasPrecision(28, 10)
                                                .HasColumnType("decimal(28,10)")
                                                .HasColumnName("PolicyToEurFxRateValue");

                                            b3.HasKey("FundValuationDetailsValuationMovementId");

                                            b3.ToTable("ValuationMovements", "PolicyValuation");

                                            b3.WithOwner()
                                                .HasForeignKey("FundValuationDetailsValuationMovementId");
                                        });

                                    b2.OwnsOne("PAS.PolicyValuation.Domain.PolicyAggregate.CurrencyRate", "PolicyToFundFxRate", b3 =>
                                        {
                                            b3.Property<long>("FundValuationDetailsValuationMovementId")
                                                .HasColumnType("bigint");

                                            b3.Property<DateOnly>("Date")
                                                .HasColumnType("date")
                                                .HasColumnName("PolicyToFundFxRateDate");

                                            b3.Property<decimal>("Value")
                                                .HasPrecision(28, 10)
                                                .HasColumnType("decimal(28,10)")
                                                .HasColumnName("PolicyToFundFxRateValue");

                                            b3.HasKey("FundValuationDetailsValuationMovementId");

                                            b3.ToTable("ValuationMovements", "PolicyValuation");

                                            b3.WithOwner()
                                                .HasForeignKey("FundValuationDetailsValuationMovementId");
                                        });

                                    b2.Navigation("FundToPolicyFxRate");

                                    b2.Navigation("Nav")
                                        .IsRequired();

                                    b2.Navigation("PolicyToEurFxRate");

                                    b2.Navigation("PolicyToFundFxRate");
                                });

                            b1.Navigation("Valuation")
                                .IsRequired();
                        });

                    b.OwnsMany("PAS.PolicyValuation.Domain.PolicyAggregate.ValuationReserve", "Reserves", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnOrder(0);

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<Guid>("FundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ValuationEventId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnOrder(1);

                            b1.HasKey("Id");

                            b1.HasIndex("ValuationEventId");

                            b1.ToTable("ValuationReserves", "PolicyValuation");

                            b1.WithOwner()
                                .HasForeignKey("ValuationEventId");

                            b1.OwnsOne("PAS.PolicyValuation.Domain.PolicyAggregate.FundValuationDetails", "Valuation", b2 =>
                                {
                                    b2.Property<long>("ValuationReserveId")
                                        .HasColumnType("bigint");

                                    b2.Property<decimal>("AmountInEur")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("AmountInEur");

                                    b2.Property<decimal>("AmountInFundCurrency")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("AmountInFundCurrency");

                                    b2.Property<decimal>("AmountInPolicyCurrency")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("AmountInPolicyCurrency");

                                    b2.Property<decimal>("RawAmountInEur")
                                        .HasPrecision(28, 10)
                                        .HasColumnType("decimal(28,10)")
                                        .HasColumnName("RawAmountInEur");

                                    b2.Property<decimal>("RawAmountInFundCurrency")
                                        .HasPrecision(28, 10)
                                        .HasColumnType("decimal(28,10)")
                                        .HasColumnName("RawAmountInFundCurrency");

                                    b2.Property<decimal>("RawAmountInPolicyCurrency")
                                        .HasPrecision(28, 10)
                                        .HasColumnType("decimal(28,10)")
                                        .HasColumnName("RawAmountInPolicyCurrency");

                                    b2.Property<decimal>("Units")
                                        .HasPrecision(28, 10)
                                        .HasColumnType("decimal(28,10)")
                                        .HasColumnName("Units");

                                    b2.HasKey("ValuationReserveId");

                                    b2.ToTable("ValuationReserves", "PolicyValuation");

                                    b2.WithOwner()
                                        .HasForeignKey("ValuationReserveId");

                                    b2.OwnsOne("PAS.PolicyValuation.Domain.PolicyAggregate.CurrencyRate", "FundToPolicyFxRate", b3 =>
                                        {
                                            b3.Property<long>("FundValuationDetailsValuationReserveId")
                                                .HasColumnType("bigint");

                                            b3.Property<DateOnly>("Date")
                                                .HasColumnType("date")
                                                .HasColumnName("FundToPolicyFxRateDate");

                                            b3.Property<decimal>("Value")
                                                .HasPrecision(28, 10)
                                                .HasColumnType("decimal(28,10)")
                                                .HasColumnName("FundToPolicyFxRateValue");

                                            b3.HasKey("FundValuationDetailsValuationReserveId");

                                            b3.ToTable("ValuationReserves", "PolicyValuation");

                                            b3.WithOwner()
                                                .HasForeignKey("FundValuationDetailsValuationReserveId");
                                        });

                                    b2.OwnsOne("PAS.PolicyValuation.Domain.PolicyAggregate.FundNav", "Nav", b3 =>
                                        {
                                            b3.Property<long>("FundValuationDetailsValuationReserveId")
                                                .HasColumnType("bigint");

                                            b3.Property<DateOnly>("Date")
                                                .HasColumnType("date")
                                                .HasColumnName("NavDate");

                                            b3.Property<decimal>("Value")
                                                .HasPrecision(28, 10)
                                                .HasColumnType("decimal(28,10)")
                                                .HasColumnName("NavValue");

                                            b3.HasKey("FundValuationDetailsValuationReserveId");

                                            b3.ToTable("ValuationReserves", "PolicyValuation");

                                            b3.WithOwner()
                                                .HasForeignKey("FundValuationDetailsValuationReserveId");
                                        });

                                    b2.OwnsOne("PAS.PolicyValuation.Domain.PolicyAggregate.CurrencyRate", "PolicyToEurFxRate", b3 =>
                                        {
                                            b3.Property<long>("FundValuationDetailsValuationReserveId")
                                                .HasColumnType("bigint");

                                            b3.Property<DateOnly>("Date")
                                                .HasColumnType("date")
                                                .HasColumnName("PolicyToEurFxRateDate");

                                            b3.Property<decimal>("Value")
                                                .HasPrecision(28, 10)
                                                .HasColumnType("decimal(28,10)")
                                                .HasColumnName("PolicyToEurFxRateValue");

                                            b3.HasKey("FundValuationDetailsValuationReserveId");

                                            b3.ToTable("ValuationReserves", "PolicyValuation");

                                            b3.WithOwner()
                                                .HasForeignKey("FundValuationDetailsValuationReserveId");
                                        });

                                    b2.OwnsOne("PAS.PolicyValuation.Domain.PolicyAggregate.CurrencyRate", "PolicyToFundFxRate", b3 =>
                                        {
                                            b3.Property<long>("FundValuationDetailsValuationReserveId")
                                                .HasColumnType("bigint");

                                            b3.Property<DateOnly>("Date")
                                                .HasColumnType("date")
                                                .HasColumnName("PolicyToFundFxRateDate");

                                            b3.Property<decimal>("Value")
                                                .HasPrecision(28, 10)
                                                .HasColumnType("decimal(28,10)")
                                                .HasColumnName("PolicyToFundFxRateValue");

                                            b3.HasKey("FundValuationDetailsValuationReserveId");

                                            b3.ToTable("ValuationReserves", "PolicyValuation");

                                            b3.WithOwner()
                                                .HasForeignKey("FundValuationDetailsValuationReserveId");
                                        });

                                    b2.Navigation("FundToPolicyFxRate");

                                    b2.Navigation("Nav")
                                        .IsRequired();

                                    b2.Navigation("PolicyToEurFxRate");

                                    b2.Navigation("PolicyToFundFxRate");
                                });

                            b1.Navigation("Valuation")
                                .IsRequired();
                        });

                    b.Navigation("Movements");

                    b.Navigation("Reserves");
                });

            modelBuilder.Entity("PAS.PolicyValuation.Domain.PolicyAggregate.Policy", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
