// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace PAS.PolicyAdmin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreatePolicyCommand : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The currencyId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyId { get; set; }
#nullable restore
#else
        public string CurrencyId { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The premiumAllocations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::PAS.PolicyAdmin.Client.Models.CreatePolicyCommandAllocationItem>? PremiumAllocations { get; set; }
#nullable restore
#else
        public List<global::PAS.PolicyAdmin.Client.Models.CreatePolicyCommandAllocationItem> PremiumAllocations { get; set; }
#endif
        /// <summary>The premiumAmount property</summary>
        public decimal? PremiumAmount { get; set; }
        /// <summary>The premiumDate property</summary>
        public Date? PremiumDate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PAS.PolicyAdmin.Client.Models.CreatePolicyCommand"/> and sets the default values.
        /// </summary>
        public CreatePolicyCommand()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PAS.PolicyAdmin.Client.Models.CreatePolicyCommand"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PAS.PolicyAdmin.Client.Models.CreatePolicyCommand CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PAS.PolicyAdmin.Client.Models.CreatePolicyCommand();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currencyId", n => { CurrencyId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "premiumAllocations", n => { PremiumAllocations = n.GetCollectionOfObjectValues<global::PAS.PolicyAdmin.Client.Models.CreatePolicyCommandAllocationItem>(global::PAS.PolicyAdmin.Client.Models.CreatePolicyCommandAllocationItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "premiumAmount", n => { PremiumAmount = n.GetDecimalValue(); } },
                { "premiumDate", n => { PremiumDate = n.GetDateValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("currencyId", CurrencyId);
            writer.WriteGuidValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::PAS.PolicyAdmin.Client.Models.CreatePolicyCommandAllocationItem>("premiumAllocations", PremiumAllocations);
            writer.WriteDecimalValue("premiumAmount", PremiumAmount);
            writer.WriteDateValue("premiumDate", PremiumDate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
