@Api_HostAddress = http://localhost:5225

### Healthy check
GET {{Api_HostAddress}}/health/

### OpenApi
GET {{Api_HostAddress}}/openapi/v1.json

### Create fund
POST {{Api_HostAddress}}/funds/collective
Content-Type: application/json
{
  "id": "b2f38c76-9811-46d8-b23e-094716fc8bba",
  "name": "Global Equity Fund",
  "isin": "BE1234567890",
  "currency": "EUR"
}

### Get fund
GET {{Api_HostAddress}}/funds/b2f38c76-9811-46d8-b23e-094716fc8bba

### Upsert fund NAV
POST {{Api_HostAddress}}/funds/b2f38c76-9811-46d8-b23e-094716fc8bba/navs
Content-Type: application/json
{
  "date": "2026-07-31",
  "value": 97.31
}