// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PAS.MarketData.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FundStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "Suspended")]
        #pragma warning disable CS1591
        Suspended,
        #pragma warning restore CS1591
        [EnumMember(Value = "Closed")]
        #pragma warning disable CS1591
        Closed,
        #pragma warning restore CS1591
    }
}
