// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PAS.MarketData.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FundType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Collective")]
        #pragma warning disable CS1591
        Collective,
        #pragma warning restore CS1591
        [EnumMember(Value = "Dedicated")]
        #pragma warning disable CS1591
        Dedicated,
        #pragma warning restore CS1591
    }
}
