// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PAS.MarketData.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetFundResult : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The currencyId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrencyId { get; set; }
#nullable restore
#else
        public string CurrencyId { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The isin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Isin { get; set; }
#nullable restore
#else
        public string Isin { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The navDecimals property</summary>
        public int? NavDecimals { get; set; }
        /// <summary>The navPricingLag property</summary>
        public int? NavPricingLag { get; set; }
        /// <summary>The navStalenessTolerance property</summary>
        public int? NavStalenessTolerance { get; set; }
        /// <summary>The status property</summary>
        public global::PAS.MarketData.Client.Models.FundStatus? Status { get; set; }
        /// <summary>The type property</summary>
        public global::PAS.MarketData.Client.Models.FundType? Type { get; set; }
        /// <summary>The unitDecimals property</summary>
        public int? UnitDecimals { get; set; }
        /// <summary>The valuationPeriodicity property</summary>
        public global::PAS.MarketData.Client.Models.FundValuationPeriodicity? ValuationPeriodicity { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PAS.MarketData.Client.Models.GetFundResult"/> and sets the default values.
        /// </summary>
        public GetFundResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PAS.MarketData.Client.Models.GetFundResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PAS.MarketData.Client.Models.GetFundResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PAS.MarketData.Client.Models.GetFundResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currencyId", n => { CurrencyId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "isin", n => { Isin = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "navDecimals", n => { NavDecimals = n.GetIntValue(); } },
                { "navPricingLag", n => { NavPricingLag = n.GetIntValue(); } },
                { "navStalenessTolerance", n => { NavStalenessTolerance = n.GetIntValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::PAS.MarketData.Client.Models.FundStatus>(); } },
                { "type", n => { Type = n.GetEnumValue<global::PAS.MarketData.Client.Models.FundType>(); } },
                { "unitDecimals", n => { UnitDecimals = n.GetIntValue(); } },
                { "valuationPeriodicity", n => { ValuationPeriodicity = n.GetEnumValue<global::PAS.MarketData.Client.Models.FundValuationPeriodicity>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("currencyId", CurrencyId);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("isin", Isin);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("navDecimals", NavDecimals);
            writer.WriteIntValue("navPricingLag", NavPricingLag);
            writer.WriteIntValue("navStalenessTolerance", NavStalenessTolerance);
            writer.WriteEnumValue<global::PAS.MarketData.Client.Models.FundStatus>("status", Status);
            writer.WriteEnumValue<global::PAS.MarketData.Client.Models.FundType>("type", Type);
            writer.WriteIntValue("unitDecimals", UnitDecimals);
            writer.WriteEnumValue<global::PAS.MarketData.Client.Models.FundValuationPeriodicity>("valuationPeriodicity", ValuationPeriodicity);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
