// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace PAS.PolicyAdmin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetPolicyResultOperationFullSurrender : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The dailySeq property</summary>
        public int? DailySeq { get; set; }
        /// <summary>The date property</summary>
        public Date? Date { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The Type property</summary>
        public global::PAS.PolicyAdmin.Client.Models.GetPolicyResultOperationFullSurrender_Type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PAS.PolicyAdmin.Client.Models.GetPolicyResultOperationFullSurrender"/> and sets the default values.
        /// </summary>
        public GetPolicyResultOperationFullSurrender()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PAS.PolicyAdmin.Client.Models.GetPolicyResultOperationFullSurrender"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PAS.PolicyAdmin.Client.Models.GetPolicyResultOperationFullSurrender CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PAS.PolicyAdmin.Client.Models.GetPolicyResultOperationFullSurrender();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dailySeq", n => { DailySeq = n.GetIntValue(); } },
                { "date", n => { Date = n.GetDateValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "$type", n => { Type = n.GetEnumValue<global::PAS.PolicyAdmin.Client.Models.GetPolicyResultOperationFullSurrender_Type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("dailySeq", DailySeq);
            writer.WriteDateValue("date", Date);
            writer.WriteGuidValue("id", Id);
            writer.WriteEnumValue<global::PAS.PolicyAdmin.Client.Models.GetPolicyResultOperationFullSurrender_Type>("$type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
