// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PAS.PolicyAdmin.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetPolicyResultOperationPremium_Type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Premium")]
        #pragma warning disable CS1591
        Premium,
        #pragma warning restore CS1591
    }
}
