<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Switch IT</Authors>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="PAS.Core" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <!-- Microsoft.OpenApi v2.0.0 referenced by Microsoft.AspNetCore.OpenApi is vulnerable -> using v2.10.0 -->
    <PackageReference Include="Microsoft.OpenApi" Version="2.10.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspNetCore.Authentication.Keycloak\PAS.AspNetCore.Authentication.Keycloak.csproj" />
  </ItemGroup>

</Project>
