// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using PAS.MarketData.Client.Currencies.Item.Fxrates;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace PAS.MarketData.Client.Currencies.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \currencies\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CurrenciesItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The fxrates property</summary>
        public global::PAS.MarketData.Client.Currencies.Item.Fxrates.FxratesRequestBuilder Fxrates
        {
            get => new global::PAS.MarketData.Client.Currencies.Item.Fxrates.FxratesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PAS.MarketData.Client.Currencies.Item.CurrenciesItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CurrenciesItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/currencies/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PAS.MarketData.Client.Currencies.Item.CurrenciesItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CurrenciesItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/currencies/{id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
