<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Switch IT</Authors>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Description>PAS Policies API client</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
    <PackageReference Include="Microsoft.Kiota.Bundle" Version="2.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\OperationResults\PAS.OperationResults.csproj" />
  </ItemGroup>

</Project>
