<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Switch IT</Authors>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="PAS.Core" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.5.2" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Cronos" Version="0.13.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
    <!-- Microsoft.OpenApi v2.0.0 referenced by Microsoft.AspNetCore.OpenApi is vulnerable -> using v2.10.0 -->
    <PackageReference Include="Microsoft.OpenApi" Version="2.10.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.11" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
  </ItemGroup>

  
  <ItemGroup>
    <ProjectReference Include="..\Core\PAS.Core.csproj" />
    <ProjectReference Include="..\Domain\PAS.Domain.csproj" />
    <ProjectReference Include="..\EntityFramework\PAS.EntityFramework.csproj" />
    <ProjectReference Include="..\OperationResults\PAS.OperationResults.csproj" />
  </ItemGroup>

</Project>
